#!/usr/bin/env bash


	executionplane --silent docker volume create confluent_poc_rest_elasticsearch_rest_elasticsearch_data_volume
	
executionplane --silent docker run -v confluent_poc_rest_elasticsearch_rest_elasticsearch_data_volume:/conteco/pwd ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/elastic/_component/_volumes/rest_elasticsearch_rest_elasticsearch_data_volume/* /conteco/pwd
		
