#!/usr/bin/env bash

export CONTECO_LABEL="confluent.poc -SolEco"
export CONTECO_DESCRIPTION="The SolEco Confluent POC solution."

export CONTECO_TYPE="confluent"
export CONTECO_NAME="poc"
export CONTECO_TAG="v1.0.4"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="soleco"
