- type: http
  id: external_ksql_ksql_server_endpoint
  name: KSQL Server External
  hosts: ["http://:8088"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "confluent_poc"
    stack: ksql
    type: external
    service: ksql_server
    area: endpoint




- type: http
  id: internal_ksql_ksql_server_endpoint
  name: KSQL Server Internal
  hosts: ["http://confluent_poc_ksql_ksql_server:8088"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "confluent_poc"
    stack: ksql
    type: internal
    service: ksql_server
    area: endpoint
