- type: http
  id: external_registry_endpoint
  name: External Registry Endpoint
  hosts: ["http://:5000"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "confluent_poc"
    stack: registry
    type: external
    service: registry
    area: endpoint
