#!/usr/bin/env bash


	executionplane --silent docker volume create confluent_poc_api_rest_kafka_connect_rest_kafka_connect_data_volume
	
executionplane --silent docker run -v confluent_poc_api_rest_kafka_connect_rest_kafka_connect_data_volume:/conteco/pwd ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/api/_component/_volumes/rest_kafka_connect_rest_kafka_connect_data_volume/* /conteco/pwd
		
