#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="package.rest_kafka_connect"
export SOLECO_MODULE_VERSION=""
export SOLECO_HIDE_COMPONENT="true"
##### END COMPONENT CONFIGURATION #####
