#!/usr/bin/env bash



executionplane --silent docker container prune --force

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_ekg_elasticsearch_volume"
	result=$(docker volume ls | grep "confluent_poc_ekg_elasticsearch_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_ekg_grafana_volume"
	result=$(docker volume ls | grep "confluent_poc_ekg_grafana_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kafka_connect_kafka_connect_secrets_volume"
	result=$(docker volume ls | grep "confluent_poc_kafka_connect_kafka_connect_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kafka_connect_kafka_connect_connect_secrets_volume"
	result=$(docker volume ls | grep "confluent_poc_kafka_connect_kafka_connect_connect_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kafka_connect_kafka_connect_data_volume"
	result=$(docker volume ls | grep "confluent_poc_kafka_connect_kafka_connect_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kafka_connect_kafka_connect_jars_volume"
	result=$(docker volume ls | grep "confluent_poc_kafka_connect_kafka_connect_jars_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kz_kafka_secrets_volume"
	result=$(docker volume ls | grep "confluent_poc_kz_kafka_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kz_kafka_data_volume"
	result=$(docker volume ls | grep "confluent_poc_kz_kafka_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kz_zookeeper_secrets_volume"
	result=$(docker volume ls | grep "confluent_poc_kz_zookeeper_secrets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kz_zookeeper_data_volume"
	result=$(docker volume ls | grep "confluent_poc_kz_zookeeper_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_kz_zookeeper_log_volume"
	result=$(docker volume ls | grep "confluent_poc_kz_zookeeper_log_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_metrics_monitor_heartbeat_data_volume"
	result=$(docker volume ls | grep "confluent_poc_metrics_monitor_heartbeat_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_metrics_monitor_heartbeat_monitors_volume"
	result=$(docker volume ls | grep "confluent_poc_metrics_monitor_heartbeat_monitors_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_metrics_overlay_metrics_overlay_volume"
	result=$(docker volume ls | grep "confluent_poc_metrics_overlay_metrics_overlay_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "confluent_poc_processor_streamsets_volume"
	result=$(docker volume ls | grep "confluent_poc_processor_streamsets_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
