#!/usr/bin/env bash


	executionplane --silent docker volume create confluent_poc_ekg_elasticsearch_volume
	
	executionplane --silent docker volume create confluent_poc_ekg_grafana_volume
	
	executionplane --silent docker volume create confluent_poc_kafka_connect_kafka_connect_secrets_volume
	
	executionplane --silent docker volume create confluent_poc_kafka_connect_kafka_connect_connect_secrets_volume
	
	executionplane --silent docker volume create confluent_poc_kafka_connect_kafka_connect_data_volume
	
	executionplane --silent docker volume create confluent_poc_kafka_connect_kafka_connect_jars_volume
	
	executionplane --silent docker volume create confluent_poc_kz_kafka_secrets_volume
	
	executionplane --silent docker volume create confluent_poc_kz_kafka_data_volume
	
	executionplane --silent docker volume create confluent_poc_kz_zookeeper_secrets_volume
	
	executionplane --silent docker volume create confluent_poc_kz_zookeeper_data_volume
	
	executionplane --silent docker volume create confluent_poc_kz_zookeeper_log_volume
	
	executionplane --silent docker volume create confluent_poc_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create confluent_poc_metrics_monitor_heartbeat_monitors_volume
	
	executionplane --silent docker volume create confluent_poc_metrics_overlay_metrics_overlay_volume
	
	executionplane --silent docker volume create confluent_poc_processor_streamsets_volume
	
executionplane --silent docker run -v confluent_poc_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/_component/_volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
