- type: http
  id: external_registry_endpoint
  name: External Registry Endpoint
  hosts: ["http://${MODECO_HOSTNAME}:5000"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: registry
    type: external
    service: registry
    area: endpoint
