#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="confluent.poc"
export SOLECO_MODULE_VERSION=""
export SOLECO_HIDE_COMPONENT="false"
##### END COMPONENT CONFIGURATION #####
